PROGRAM=KMeans

SOURCE_FILES=${PROGRAM}.java \
	Random.java \
	Cluster.java \
	Normal.java \
	Common.java \
	GlobalArgs.java 

NUM_OOO_WORKERS=24
NUM_RCR_WORKERS=23

BMFLAGS= -heapsize-mb 5000

include ../master-makefile
